title: Alexander's Domain of Mathematics
email: lextmcdowell@gmail.com
description: >-
  My blog and portfolio. A collection of the various projects, publications, and music I have made.
baseurl: ""
url: "https://alexander-mcdowell.github.io"
github_username: alexander-mcdowell

markdown: kramdown
kramdown:
   math_engine: mathjax

theme: minima
plugins:
  - jekyll-seo-tag

exclude: ['README.md',
          'projects/CS114-Final-Project/README.md',
          'projects/GraphVisualizer/README.md',
          'projects/ShenzhenSolitaire/README.md',
          .sass-cache/,
          .jekyll-cache/,
          Gemfile,
          Gemfile.lock]